openapi: 3.0.1
info:
  title: PDF Question Answering API
  description: API for extracting text from PDF files and performing question answering on the extracted text.
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /process_pdf:
    post:
      summary: Process a PDF file and perform question answering
      operationId: processPdf
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_link:
                  type: string
                  description: The Google Drive link to the PDF file
                question:
                  type: string
                  description: The question to be answered
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The answer to the question





